# Generated by Django 5.2.5 on 2025-08-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Travel ID')),
                ('type', models.CharField(choices=[('flight', 'Flight ✈️'), ('train', 'Train 🚆'), ('bus', 'Bus 🚌')], help_text='Choose your transport Mode', max_length=10, verbose_name='Travel Type')),
                ('source', models.CharField(help_text='Departure city', max_length=100, verbose_name='From City')),
                ('destination', models.CharField(help_text='Arrival city', max_length=100, verbose_name='To City')),
                ('departure_date', models.DateField(help_text='When does the journey start?', verbose_name='Departure Date')),
                ('departure_time', models.TimeField(help_text='What time does it leave?', verbose_name='Departure Time')),
                ('arrival_date', models.DateField(help_text='When will you reach?', verbose_name='Arrival Date')),
                ('arrival_time', models.TimeField(help_text='What time will you arrive?', verbose_name='Arrival Time')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost for one person', max_digits=10, verbose_name='Price per Seat')),
                ('available_seats', models.PositiveIntegerField(help_text='How many seats are left?', verbose_name='Available Seats')),
                ('total_seats', models.PositiveIntegerField(help_text='Maximum capacity', verbose_name='Total Seats')),
                ('status', models.CharField(choices=[('available', 'Available ✅'), ('full', 'Fully Booked 🔴'), ('cancelled', 'Cancelled ❌')], default='available', max_length=10, verbose_name='Booking Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added On')),
            ],
            options={
                'verbose_name': 'Travel Option',
                'verbose_name_plural': 'Travel Options',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
    ]
