# Generated by Django 5.2.5 on 2025-08-21 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Booking ID')),
                ('number_of_seats', models.PositiveIntegerField(help_text='How many seats were booked?', verbose_name='Number of Seats')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total cost for all seats', max_digits=10, verbose_name='Total Amount')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this booking made?', verbose_name='Booked On')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed ✅'), ('cancelled', 'Cancelled ❌'), ('pending', 'Pending ⏳')], default='confirmed', max_length=10, verbose_name='Booking Status')),
                ('passenger_details', models.JSONField(blank=True, default=dict, help_text='Additional passenger details', verbose_name='Passenger Information')),
                ('travel_option', models.ForeignKey(help_text='Which travel option was booked?', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.traveloption', verbose_name='Travel Details')),
                ('user', models.ForeignKey(help_text='Who made this booking?', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
