# Generated by Django 5.2.5 on 2025-08-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveloption',
            options={'ordering': ['departure_date', 'departure_time']},
        ),
    ]
