# Generated by Django 5.2.5 on 2025-08-21 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_traveloption_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Your contact number for booking updates', max_length=15, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, help_text='When were you born?', null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, help_text='Your complete address', verbose_name='Home Address')),
                ('city', models.CharField(blank=True, help_text='Which city do you live in?', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='Your state or province', max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default='India', help_text='Which country are you from?', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, help_text='Your area postal code', max_length=10, verbose_name='Postal Code')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Someone to contact in case of emergency', max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text="Emergency contact's phone number", max_length=15, verbose_name='Emergency Contact Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
        ),
    ]
